repos:
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/isort
    rev: 6.0.0
    hooks:
    -   id: isort
        args:
            - --profile=black
